apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ubuntu"
    port: 81
  selector:
    app: ubuntu
